### ISSUE TITLE
apps::backup::veeam::local::plugin problems

### ISSUE THREAD

**Issue by Cool34000** [centreon/centreon-nsclient-build#13]
Hi,

I think I found 2 bugs in Veeam Plugin.

* 1st, jobs with non standard characters make the plugin fail.

I have a server where one of the jobs is called "Réplication vCSA". Here's the result:
`# /usr/lib64/nagios/plugins/check_centreon_nrpe -H x.x.x.x -p 5666 -t 55 -u -m 8192 -c check_centreon_plugins -a 'apps::backup::veeam::local::plugin' 'job-status' ' --filter-name="" --filter-start-time="" --filter-end-time="86400" --filter-counters="" --ok-status="%{is_running} == 0 and %{status} =~ /Success/i" --warning-status="%{is_running} == 0 and %{status} =~ /Warning/i" --critical-status="%{is_running} == 0 and %{status} =~ /Failed/i" --warning-long="" --critical-long="" --verbose'`

`UNKNOWN: Cannot decode json response: malformed UTF-8 character in JSON string, at character offset 226 (before "\x{fffd}plication vC...") at C:\Windows\TEMP\par-5352562d4241434b555024\cache-e911f522c2e788f4c9128b42d8f6076582f7d9e4\inc\lib/apps/backup/veeam/local/mode/jobstatus.pm line 173.`
If I rename the job (replace "é" with "e"), it's working.

* 2nd, mode "tape-jobs" isn't working at all:
`# /usr/lib64/nagios/plugins/check_centreon_nrpe -H 10.20.1.234 -p 5666 -t 55 -u -m 8192 -c check_centreon_plugins -a 'apps::backup::veeam::local::plugin' 'tape-jobs' ' --verbose'  `                                          
```
UNKNOWN: Cannot load module --mode.
Can't locate apps/backup/veeam/local/mode/tapejobs.pm in @INC (you may need to install the apps::backup::veeam::local::mode::tapejobs module) (@INC contains: C:/Program Files/centreon-nsclient/NSClient++/scripts/centreon C:\Windows\TEMP\par-5352562d4241434b555024\cache-e911f522c2e788f4c9128b42d8f6076582f7d9e4\inc\lib C:\Windows\TEMP\par-5352562d4241434b555024\cache-e911f522c2e788f4c9128b42d8f6076582f7d9e4\inc CODE(0x2767410) CODE(0x2767608)) at C:\Windows\TEMP\par-5352562d4241434b555024\cache-e911f522c2e788f4c9128b42d8f6076582f7d9e4\inc\lib/centreon/plugins/misc.pm line 222.
```
I took a look at "C:\Windows\Temp\par-5352562d4241434b555024\cache-e911f522c2e788f4c9128b42d8f6076582f7d9e4\inc\lib\apps\backup\veeam\local\mode" and tapejobs.pm is missing

**Comment by Cool34000** [comment]
For the tape-jobs mode, if I download the 2 missing files from [here](https://github.com/centreon/centreon-plugins/blob/9b78f5274c44a63c6d8b70e7a98519eb08950326/apps/backup/veeam/local/mode/tapejobs.pm) and [here](https://github.com/centreon/centreon-plugins/blob/9b78f5274c44a63c6d8b70e7a98519eb08950326/centreon/common/powershell/veeam/tapejobs.pm) then put them in according folders, it's working...

**Comment by garnier-quentin** [comment]
I have added it in build script.

**Comment by garnier-quentin** [comment]
Could you display the json output ? --ps-exec-only

**Comment by Cool34000** [comment]
I only renamed 1 jobs out of 2:
`[{"type":1,"endTimeUTC":"1588803563,057","creationTimeUTC":"1588803223,877","name":"Replication vCSA vers ESX3","isRunning":false,"result":0},{"type":1,"endTimeUTC":"1588803217,677","creationTimeUTC":"1588802830,213","name":"Rplication vCSA vers ESX2","isRunning":false,"result":0},{"type":0,"endTimeUTC":"1588800513,573","creationTimeUTC":"1588795213,637","name":"Sauvegarde du DataCenter (locale)","isRunning":false,"result":1}]`

**Comment by garnier-quentin** [comment]
I don't see the special character. Could you copy the result in a file ? (and send it to me)

**Comment by Cool34000** [comment]
it's not there even in PuTTY

**Comment by garnier-quentin** [comment]
If you redirect in a file, it should be in the file. And i could read it with a emacs hexl-mode

**Comment by Cool34000** [comment]
Sorry, I misunderstood...
There is a "," instead of the "é"... It's an ANSI encoded file... As if it was DOS output and not PowerShell

**Comment by garnier-quentin** [comment]
The "é" is encoded as 0x82. It looks like CP1252. I'm not sure

**Comment by garnier-quentin** [comment]
Could you try to add: 
```
      $stdout = encode('UTF-8', $stdout);
      $decoded = JSON::XS->new->utf8->decode($stdout);
```

**Comment by Cool34000** [comment]
`UNKNOWN: Cannot decode json response: Undefined subroutine &apps::backup::veeam::local::mode::jobstatus::encode called at C:\Windows\TEMP\par-5352562d4241434b555024\cache-e911f522c2e788f4c9128b42d8f6076582f7d9e4\inc\lib/apps/backup/veeam/local/mode/jobstatus.pm line 173.`

**Comment by garnier-quentin** [comment]
Add that also (beginning of the file):
```
use Encode qw(decode encode);
``

**Comment by Cool34000** [comment]
Working!

```
package apps::backup::veeam::local::mode::jobstatus;

use base qw(centreon::plugins::templates::counter);

use strict;
use warnings;
use centreon::common::powershell::veeam::jobstatus;
use apps::backup::veeam::local::mode::resources::types qw($job_type $job_result);
use centreon::plugins::templates::catalog_functions qw(catalog_status_threshold catalog_status_calc);
use centreon::plugins::misc;
use JSON::XS;

use Encode qw(decode encode);

sub custom_status_output {
...
```

**Comment by garnier-quentin** [comment]
Ok i will update it.

**Comment by Sims24** [comment]
@garnier-quentin I assume that it's OK now? If not, please create a relevant MONIC ticket so we can keep track of this ;) 

Thx

**Comment by Cool34000** [comment]
Cordialement,
Sylvain Gomez
06 77 01 26 61
http://www.wifi-hotspots.fr

Envoyé depuis mon smartphone
