### ISSUE TITLE
Embedded plugin configuration files ?

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-nsclient-build#15]
Hi,

Some plugins need a configuration file, I think about `qwinsta.xml` and `dcdiag.xml`.
For now these configuration files sit next to `centreon_plugins.exe`.

Is there any way to put these default `.xml` configuration files into the `centreon_plugins.exe` binary archive, so that the plugins which need them would point their `--config` option to these embedded files by default ?
Would rather be convenient.

Thank you 👍

**Comment by garnier-quentin** [comment]
Maybe i could put it directly in centreon_plugins (in the code)

**Comment by UrBnW** [comment]
Would be the best solution I think yes 👍
