### ISSUE TITLE
Development build ?

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-nsclient-build#16]
Hi,

After every commit in the `centreon-plugins` repository, the corresponding rpm packages are built and made available in the `unstable` repository.

Is there any place where we could also find the unstable `centreon_plugins.exe` built accordingly ?

Would really be convenient.

Many thanks 👍

**Comment by Sims24** [comment]
Hi @UrBnW 

Thanks for sharing your thoughts. 

We will not create a Windows-based build infrastructure only for this purpose. It would be overkill as only few centreon-plugins are included in the .exe. Most of the time a new centreon_plugins release doesn't have any consequence on the .exe content.

We shared this repository with the community so everyone can build things like that if they need it :)

Simon

**Comment by UrBnW** [comment]
Hi @Sims24,
Understood :)
Note that there are some free CIs you can connect to a GitHub repository which support Windows. I think about Travis for example.
Anyway, thank you very much for your feedback 👍 :)
