### ISSUE TITLE
Nsclient build + latest changes

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-nsclient-build#23]
Hi all,
i notice that in configuration file version still 20200602 and when i try using local iis plugin with --filter-name switch i got this error @garnier-quentin 

[root@xxx ~]# /usr/lib/nagios/plugins//check_centreon_nrpe3 -H XXX -p 5666 -2 -P 8192 -n -c check_centreon_plugins -a 'apps::iis::local::plugin' 'applicationpool-state' '--filter-name=CreditoPool'

Unknown option: filter-name at C:\Windows\TEMP\par-45554954504f5057534e30303424\cache-d8d133336a6054ae0c3a8a3ab49b191ecf0a4127\inc\lib/centreon/plugins/alternative/Getopt.pm line 67.

Thanks

**Comment by R00T88** [comment]
@kabreu im adding you so maybe can help too

Thanks

**Comment by R00T88** [comment]
hi @kabreu 
i think last exe build don't take in consider latest centreon plugin commit because iis local plugin still search for --pools parameters but it's removed

[root@euitpopcen004 ~]# /usr/lib/nagios/plugins//check_centreon_nrpe3 -H XXX -p 5666 -2 -P 8192 -n -c check_centreon_plugins -a 'apps::iis::local::plugin' 'applicationpool-state'
UNKNOWN: Need to specify at least '--pools' or '--auto' option.

**Comment by Sims24** [comment]
Hi @R00T88 , 

Sorry for the late answer. We are thinking about it. 

Simon

**Comment by UrBnW** [comment]
@R00T88 You should be able to find last version there :
https://github.com/centreon/centreon-nsclient-build/releases
