### ISSUE TITLE
No output returned from plugin - Nsclient

### ISSUE THREAD

**Issue by HeroIT80** [centreon/centreon-nsclient-build#46]
I have installed NRPE on centreon. However when added a host and use the template, it returned the error. 

Upon investigate, I found the execute check command line is /usr/lib64/nagios/plguin// check_centreon_nrpe. 

If I manual type /usr/lib/nagio/plugin//check_centreon_nrpe" it worked. 

How can I change the default command point to lib instead lib64? 
![error](https://user-images.githubusercontent.com/78196361/108618917-c1abb100-745c-11eb-801a-090e343dd4aa.jpg)

**Comment by Sims24** [comment]
Hi @HeroIT80 

Please copy/paste the check_centreon_nrpe or create a symbolic link. 

It's a packaging issue not related with the NSClient build. 

Thanks
