### ISSUE TITLE
Can't use the Webserver

### ISSUE THREAD

**Issue by JudikaelNedev** [centreon/centreon-nsclient-build#89]
Hello,
I'm just trying to access the the web with a fresh new install of Centreon NSClient++.
I have tried to insert manually a password, I tried the commands `nscp web -- password -set 123`, the `nscp web install --password=123` and I also tried to insert à `password = 123` in the nsclient.ini **[/settings/WEB/server]** or **/settings/default**

Behavior that I saw : 
When connecting to the page the console is giving errors :
```
glyphicons-halflings-regular.woff2:1 

       Failed to load resource: the server responded with a status of 404 ()
fontawesome-webfont.woff2:1 

       Failed to load resource: the server responded with a status of 404 ()
login.js:11 Is logged inS
jquery-1.11.1.min.js:4 
```
.
If I type the wrong password, the page is correctly telling me that the password is incorrect

If I type the correct password, the password prompt is still there without error but in the console i'm seeing 403 forbidden messages.
And I cannot navigate to the other menus. _(Even tho I can see a "Is logged in" in the logs)_
![image](https://github.com/centreon/centreon-nsclient-build/assets/125652155/c6416e3c-397a-4a87-88bd-bc48cfd8615b)

I have tried with Brave and Edge.

I'm joining you the nsclient.logs and web console logs :
[localhost-1704456102076.log](https://github.com/centreon/centreon-nsclient-build/files/13841799/localhost-1704456102076.log)

[nsclient.log](https://github.com/centreon/centreon-nsclient-build/files/13841802/nsclient.log)

I've tried with versions 
- Centreon-NSClient-0.5.2.41-20211102-x64.exe
- Centreon-NSClient-0.5.2.41-20210427-x64.exe

**Comment by omercier** [comment]
Hi,
Sorry, we don't maintain NSClient++, the goal of this repository is to help building your own installer with Centreon's plugins and configuration, and to provide our own builds in the release section.
For your particular issue, please have a look [here](https://nsclient.org/#getting-help).
Regards
